# Generated by Django 5.2.1 on 2025-05-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("paypal", "paypal"), ("transfer", "Перевод на счет")],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
