# Generated by Django 5.2.1 on 2025-06-22 19:42

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
