# Generated by Django 5.2.1 on 2025-05-25 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название курса",
                        max_length=150,
                        verbose_name="Курс",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Добавьте превью",
                        upload_to="materials/images",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Укажите описание", verbose_name="Описание"
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название урока",
                        max_length=150,
                        verbose_name="Урок",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Добавьте превью",
                        upload_to="materials/images",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Укажите описание", verbose_name="Описание"
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        help_text="Добавьте ссылку на видео",
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите курс",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
