# Generated by Django 5.2.1 on 2025-05-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте превью",
                null=True,
                upload_to="materials/images",
                verbose_name="Превью",
            ),
        ),
    ]
