# Generated by Django 5.2.1 on 2025-05-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте превью",
                null=True,
                upload_to="materials/images",
                verbose_name="Превью",
            ),
        ),
    ]
