# Generated by Django 5.2.1 on 2025-06-16 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_course"),
        ("materials", "0005_course_owner_alter_lesson_owner"),
    ]

    operations = []
