# Generated by Django 5.2.1 on 2025-06-23 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0008_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
